### ISSUE TITLE
Inconsistent Data Types

### ISSUE THREAD

**Issue by scottrick** [swccgpc/swccg-card-json#42]
In my work using this repo, I've noticed a few things:
1) Sometimes there are fields in the json set to null, when most of the time if they are null they simply don't appear.
2) The fields are not always in the same order.  This is mainly an annoyance when I'm working on writing code to output an updated json file, since I get lots of diffs when its essentially the same.  I'd love to update this to be consistent.
3) The fields for 
```
        "destiny"
        "power"
        "ability"
        "maneuver"
        "armor"
        "hyperspeed"
        "landspeed"
        "politics"
        "deploy"
```
are usually of the Number type, but ocassionally, they are a String.  This is to handle cards such as the Brainiac, or anything with an asterisk.

The first two issues are easy to fix.  For the third, I think we should either always represent them as Strings, or always as Numbers.  If we use Numbers, we should set them to null in the situations where we currently have an asterisk.  This way the data is consistently either a String or a Number.  

I'm happy to make these changes, but I'm concerned about the impact (if any) such changes would have on the scomp link.  Thoughts?

**Comment by thomasmarlin** [comment]
I agree that 1 and 2 should be addressed. For #2, I prefer having the field as missing rather than assigned as null. 

#3 is definitely trickier. I agree we should have a common data-type. I agonized about this one for quite a while. Numbers are definitely easier for comparisons and sorting, but Strings are probably more accurate.  You mentioned "*" values, but we also have Pi and also dual-destiny cards like R2iR5, etc. 

Currently, Scomp relies on the values being numbers for it's numeric comparisons. If we shift away from that, I would have to make a change to Scomp, but that should be pretty trivial. If Strings work good for Comlink, let's move forward with that. If that works, just post back here and I'll make the change in Scomp to handle either data type so it's ready.

**Comment by scottrick** [comment]
Strings sound great.  I will put up a CR later today fixing #1 and updating the mentioned values to all be Strings.  Strings seem to make the most sense to me since it can handle the odd "*" and "2 or 5" cases.
