### ISSUE TITLE
Inconsistencies between Scomp Link and Gemp

### ISSUE THREAD

**Issue by scottrick** [swccgpc/swccg-card-json#46]
When mapping this json data to the gemp card ids, I found a few issues.  I listed them in the order of importance.  

1. Cards that do not exist in Gemp, but do exist here.  Are these real cards, or can we delete them?
 - Don't Do That Again (Tatooine) (V)
 - Your Insight Serves You Well (Death Star II) (V)
 - Fanfare (Tatooine) (V)
 - You Cannot Hide Forever (Death Star II) (V)

2. Cards in different sets.  
 - Your Ship? (V) - In Gemp this card is marked as in the Virtual Premium set, but in Scomp Link its marked as Virtual Set 0. 

3. Cards with typos / incorrect image urls.
 - Endor Commando Team - Image url in Scomp Link is mispelled:  endorrcommandoteam.gif 
 - Help Me Obi-Wan Kenobi & Quite A Mercenary - Image url in Scomp Link is missing ampersand, while Gemp url has the ampersand.  Other combo cards do contain the ampersand.

I'm happy to make the necessary changes for 1 & 2, but I'm not sure where we would make a change to fix 3.  Thoughts?

**Comment by thomasmarlin** [comment]
#1:  Yup - These are real and should have the same text as their defensive-shield counterparts.  The idea was that people could print out a slip to go over their existing effects.

#2:  Yeah, that's a weird one.  I think the Virtual Premium Set is probably more correct. I know we put it there in GEMP because it was released between sets.   Took me a LONG time to dig up the PDF for that one!!

#3:  I've duplicated those images and put them at the following URLS:
http://res.starwarsccg.org/cards/Images-HT/starwars/Virtual3-Light/large/endorcommandoteam.gif
http://res.starwarsccg.org/cards/Images-HT/starwars/Virtual13-Light/large/helpmeobiwankenobi&quiteamercenary.gif

Let's update the DB to point to those new ones.

**Comment by DevoKun** [comment]
That path is not correct.
`http://res.starwarsccg.org/cards/Images-HT/starwars/Virtual3-Light/large/endorcommandoteam.gif`
The URL should be `https://res.starwarsccg.org/cards/Virtual3-Light/large/endorcommandoteam.gif`

**Comment by scottrick** [comment]
Excellent. 

1. I will map those four cards to the same gemp Id as the defensive-shield counterparts then.
2. I wlil update Your Ship? to be in the virtual premium set.
3. I'll update the urls, thanks for adding them.

**Comment by scottrick** [comment]
CR is up with these changes.  I created a new issue to discuss the image urls.
